grafana:
  enabled: true
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
      service.beta.kubernetes.io/aws-load-balancer-security-groups: "<put_the_sg>>"  # Using retrieved security group ID
    type: LoadBalancer
    labels:
      app: grafana
  extraLabels:
    app: grafana
  adminPassword: "admin"  # Example: setting the admin password
