prometheus:
  service:

    type: LoadBalancer
    labels:
      app: prometheus
    extraLabels:
      app: prometheus
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
      service.beta.kubernetes.io/aws-load-balancer-security-groups: "<put_the_sg>"
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector:
      matchLabels:
        release: prometheus-operator
    podMonitorSelector:
      matchLabels:
        release: prometheus-operator
    serviceAccountName: prometheus-operator-prometheus
    externalLabels:
      app: prometheus

