apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tsunami-scanner.fullname" . }}
  annotations:
    {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  labels:
    {{- include "tsunami-scanner.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "tsunami-scanner.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "tsunami-scanner.name" . }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          {{- range .Values.service.ports }}
          - name: {{ .name }}
            containerPort: {{ .targetPort }}
          {{- end }}
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
