name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      uuid:
        description: 'UUID of the Terraform plan to apply'
        required: true

jobs:
  apply:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::654654392619:role/github-actions-role
          aws-region: us-west-2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7

      - name: Initialize Terraform
        run: terraform init

      - name: Download Plan from S3
        run: |
          aws s3 cp s3://my-terraform-plan-block-apply-bucket-github-override/${{ github.event.inputs.uuid }}-plan.out plan.out

      - name: Terraform Apply
        run: terraform apply plan.out
