name: Terraform Plan

on:
  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::<ACCOUNT_ID>:role/github-actions-role
          aws-region: us-west-2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=plan.out

      - name: Upload Plan
        uses: actions/upload-artifact@v2
        with:
          name: terraform-plan-${{ github.run_id }}
          path: plan.out
