name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'The run ID of the Terraform Plan to apply'
        required: true

jobs:
  apply:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::654654392619:role/github-actions-role
          aws-region: us-west-2

      - name: Download Plan
        uses: actions/download-artifact@v2
        with:
          name: terraform-plan-${{ github.event.inputs.run_id }}
          path: ./plan.out

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Apply
        run: terraform apply ./plan.out
